version: "3.8"

services:
  app:
    build: .
    container_name: codemastery-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=switchback.proxy.rlwy.net
      - DB_PORT=54448
      - DB_USER=root
      - DB_PASSWORD=bpHrLGxGcpPLThecGEYRNhnCraXBlwbd
      - DB_NAME=codemastery
      
      # Incluye también tus variables de NextAuth y Google OAuth
      - NEXTAUTH_URL=https://codemasterypi-production.up.railway.app
      - NEXTAUTH_SECRET=6bf82c71e4bbb38face199d3262e76db
      - GOOGLE_CLIENT_ID=1032118627953-7633895lbrnp3e9nfqs066qmces7j6m6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      
    networks:
      - codemastery-net

networks:
  codemastery-net:
